import type { ClubhouseActivity } from '../types';

export const CLUBHOUSE_ACTIVITIES: ClubhouseActivity[] = [
    {
        id: 'team_night_out',
        name: 'Send the Lads Out!',
        irishName: 'Cuir na Buachaillí Amach!',
        description: 'A night on the town — pints, craic, and tall tales until the small hours. The lads needed it and they know it.',
        moraleBoost: 18,
        fitnessImpact: -8,
        trainingEffectDays: 5,
        cooldownDays: 21,
        cost: 'low',
    },
    {
        id: 'trip_new_york',
        name: 'Send the Lads to New York!',
        irishName: 'Cuir na Buachaillí go Nua Eabhrac!',
        description: 'Long weekend in the Big Apple. The Bronx, Times Square, a few céilí bars in Woodside, and one very sore Tuesday morning back at training.',
        moraleBoost: 45,
        fitnessImpact: -20,
        trainingEffectDays: 14,
        cooldownDays: 90,
        cost: 'high',
    },
    {
        id: 'golf_day',
        name: 'Take the Lads Golfing!',
        irishName: 'Tóg na Buachaillí ag Imirt Gailf!',
        description: 'Eighteen holes, a bit of slagging, and a post-round pint at the clubhouse. Nobody plays well but everyone has the craic.',
        moraleBoost: 12,
        fitnessImpact: -2,
        trainingEffectDays: 2,
        cooldownDays: 14,
        cost: 'low',
    },
    {
        id: 'ceili_mor',
        name: 'Throw a Céilí!',
        irishName: 'Céilí Mór a Eagrú!',
        description: 'Live trad music, set dancing, and the whole community packed into the parish hall. The spirit goes through the roof.',
        moraleBoost: 22,
        fitnessImpact: -5,
        trainingEffectDays: 3,
        cooldownDays: 28,
        cost: 'medium',
    },
    {
        id: 'team_dinner',
        name: 'County Board Dinner Night!',
        irishName: 'Oíche Dinnéir na Comhairle Contae!',
        description: 'Black tie, speeches, a few awards, and the county board buying the wine for once. Builds real pride in the jersey.',
        moraleBoost: 14,
        fitnessImpact: -3,
        trainingEffectDays: 2,
        cooldownDays: 30,
        cost: 'medium',
    },
    {
        id: 'lanzarote_trip',
        name: 'Send the Lads to the Canaries!',
        irishName: 'Cuir na Buachaillí go dtí na hOileáin Chanáracha!',
        description: 'Four days in Lanzarote — sun, sea, and about twenty minutes of actual training. Everyone comes back smiling and slightly sunburned.',
        moraleBoost: 35,
        fitnessImpact: -10,
        trainingEffectDays: 7,
        cooldownDays: 60,
        cost: 'high',
    },
    {
        id: 'five_a_side',
        name: 'Five-a-Side Blitz!',
        irishName: 'Blitz Cúig in Aghaidh Cúig!',
        description: 'An internal five-a-side tournament in the car park. Pure craic, dodgy goals, and a winner\'s medal made from tinfoil. Exactly what\'s needed.',
        moraleBoost: 10,
        fitnessImpact: 0,
        trainingEffectDays: 0,
        cooldownDays: 14,
        cost: 'low',
    },
    {
        id: 'visit_gaeltacht',
        name: 'Send the Lads to the Gaeltacht!',
        irishName: 'Cuir na Buachaillí go dtí an Ghaeltacht!',
        description: 'A weekend in Connemara — cold swims, mountain hikes, campfire sessions as Gaeilge, and stars you can\'t see in the city. Does something to the soul.',
        moraleBoost: 20,
        fitnessImpact: -4,
        trainingEffectDays: 3,
        cooldownDays: 45,
        cost: 'medium',
    },
    {
        id: 'bbq_day',
        name: 'Fire Up the BBQ!',
        irishName: 'Lasaigí an Barbacú!',
        description: 'Sausages, burgers, and cans in the car park after training. Costs nothing. Fixes everything.',
        moraleBoost: 8,
        fitnessImpact: -1,
        trainingEffectDays: 1,
        cooldownDays: 10,
        cost: 'low',
    },
    {
        id: 'boston_tour',
        name: 'Send the Lads to Boston!',
        irishName: 'Cuir na Buachaillí go Boston!',
        description: 'A week in Boston — exhibition matches, diaspora dinners, a session in Doyle\'s on Washington Street, and nights that will be talked about for years.',
        moraleBoost: 50,
        fitnessImpact: -25,
        trainingEffectDays: 18,
        cooldownDays: 120,
        cost: 'high',
    },
];
