import type { ClubhouseActivity } from '../types';

export const CLUBHOUSE_ACTIVITIES: ClubhouseActivity[] = [
    {
        id: 'team_night_out',
        name: 'Team Night Out',
        irishName: 'Oíche Amach don Fhoireann',
        description: 'A night on the town — pints, craic, and stories. The lads needed it.',
        moraleBoost: 18,
        fitnessImpact: -8,
        trainingEffectDays: 5,
        cooldownDays: 21,
        cost: 'low',
    },
    {
        id: 'trip_new_york',
        name: 'Trip to New York',
        irishName: 'Turas go Nua Eabhrac',
        description: 'The squad heads to New York for a long weekend. The Bronx, Broadway, and a few céilí bars. Morale goes through the roof but fitness takes a hit.',
        moraleBoost: 45,
        fitnessImpact: -20,
        trainingEffectDays: 14,
        cooldownDays: 90,
        cost: 'high',
    },
    {
        id: 'golf_day',
        name: 'Golf Day',
        irishName: 'Lá Gailf',
        description: 'A relaxed day on the golf course — good craic, light competition, fresh air. The lads come back refreshed.',
        moraleBoost: 12,
        fitnessImpact: -2,
        trainingEffectDays: 2,
        cooldownDays: 14,
        cost: 'low',
    },
    {
        id: 'ceili_mor',
        name: 'Big Céilí',
        irishName: 'Céilí Mór',
        description: 'A proper céilí with live music, dancing and the full community behind the team. Sets the spirit soaring.',
        moraleBoost: 22,
        fitnessImpact: -5,
        trainingEffectDays: 3,
        cooldownDays: 28,
        cost: 'medium',
    },
    {
        id: 'team_dinner',
        name: 'County Board Banquet',
        irishName: 'Fleadh na Comhairle Contae',
        description: 'A formal black-tie dinner hosted by the county board — speeches, awards, and a real sense of pride in the jersey.',
        moraleBoost: 14,
        fitnessImpact: -3,
        trainingEffectDays: 2,
        cooldownDays: 30,
        cost: 'medium',
    },
    {
        id: 'lanzarote_trip',
        name: 'Warm-Weather Training Camp',
        irishName: 'Campa Traenála Teasaí',
        description: 'Four days in the Canaries — sun, sea, and some light training thrown in for good measure. Everyone comes back with a smile.',
        moraleBoost: 35,
        fitnessImpact: -10,
        trainingEffectDays: 7,
        cooldownDays: 60,
        cost: 'high',
    },
    {
        id: 'five_a_side',
        name: '5-a-Side Tournament',
        irishName: 'Comórtas Cúig-in-Aghaidh-Cúig',
        description: 'An internal 5-a-side blitz — pure craic, plenty of goals, and a winners\' medal made from tinfoil. Brilliant for team bonding.',
        moraleBoost: 10,
        fitnessImpact: 0,
        trainingEffectDays: 0,
        cooldownDays: 14,
        cost: 'low',
    },
    {
        id: 'visit_gaeltacht',
        name: 'Gaeltacht Weekend',
        irishName: 'Deireadh Seachtaine sa Ghaeltacht',
        description: 'A weekend in the Gaeltacht — swimming, hiking, campfire sessions, and total Irish immersion. Spiritual fuel for the season ahead.',
        moraleBoost: 20,
        fitnessImpact: -4,
        trainingEffectDays: 3,
        cooldownDays: 45,
        cost: 'medium',
    },
    {
        id: 'bbq_day',
        name: 'Training Ground BBQ',
        irishName: 'Barbacú ag an gClós',
        description: 'Sausages, burgers, and laughter in the car park after training. Simple but exactly what the squad needed.',
        moraleBoost: 8,
        fitnessImpact: -1,
        trainingEffectDays: 1,
        cooldownDays: 10,
        cost: 'low',
    },
    {
        id: 'boston_tour',
        name: 'Boston Fundraiser Tour',
        irishName: 'Camchuairt go Boston',
        description: 'A week in Boston playing exhibition matches and meeting the diaspora. Fundraising, culture, and absolutely heroic nights out.',
        moraleBoost: 50,
        fitnessImpact: -25,
        trainingEffectDays: 18,
        cooldownDays: 120,
        cost: 'high',
    },
];
